"use client";

import type { Metadata } from "next";
import { Overpass } from "next/font/google";
import { Quantico } from "next/font/google";

import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

import Navbar from '@/components/navBar';
import { UserContextProvider } from "@/contexts/userContext";
import { LoadingProvider } from "@/contexts/loadingOverlayContext";

import "./globals.css";

const overpass = Overpass({
  subsets: ['latin'],
  variable: "--font-overpass",
});

const quantico = Quantico({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: "--font-quantico",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${quantico.variable} ${overpass.variable} antialiased`}
      >
        <LoadingProvider>
          <UserContextProvider>
            <Navbar />
            <div className="app">
              {children}
            </div>
            <ToastContainer />
          </UserContextProvider>
        </LoadingProvider>
      </body>
    </html>
  );
}
