import type { Metadata } from "next";
import { Suspense } from "react";
import { Overpass } from "next/font/google";
import { Bebas_Neue } from "next/font/google";
import { Quantico } from "next/font/google";

import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

import Navbar from '@/components/navBar';
import LoadingOverlay from "@/components/loadingOverlay";
// import { UserContextProvider } from "@/contexts/userContext";
import { LoadingProvider } from "@/contexts/loadingOverlayContext";

import "./globals.css";

const overpass = Overpass({
  subsets: ['latin'],
  variable: "--font-overpass",
});

const bebas = Bebas_Neue({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-bebas',
});

const quantico = Quantico({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: "--font-quantico",
});

export const metadata: Metadata = {
  title: "Autofourms",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${quantico.variable} ${overpass.variable} ${bebas.variable} antialiased`}
      >

        {/* <LoadingProvider> */}
          {/* <UserContextProvider> */}
            <Navbar />
            <Suspense fallback={<LoadingOverlay isLoading />}>

              <div className="app">
                {children}
              </div>
            </Suspense>

            <ToastContainer />
          {/* </UserContextProvider> */}
        {/* </LoadingProvider> */}
      </body>
    </html>
  );
}
