import type { Metadata } from "next";
import { Suspense } from "react";
import { Overpass } from "next/font/google";
import { Bebas_Neue } from "next/font/google";
import { Quantico } from "next/font/google";

import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

import Navbar from '@/components/navBar';
import LoadingOverlay from "@/components/loadingOverlay";
import { getAuthenticatedAppForUser } from "@/lib/firebase/serverApp";

import "./globals.css";

export const overpass = Overpass({
  subsets: ['latin'],
  variable: "--font-overpass",
});

export const bebas = Bebas_Neue({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-bebas',
});

export const quantico = Quantico({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: "--font-quantico",
});

export const metadata: Metadata = {
  title: "Autoforums",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const { currentUser } = await getAuthenticatedAppForUser();

  return (
    <html lang="en">
      <body
        className={`${quantico.variable} ${overpass.variable} ${bebas.variable} antialiased`}
      >
        <Navbar initialUser={currentUser?.toJSON()} />
        <Suspense fallback={<LoadingOverlay isLoading />}>
          <div className="app">
            {children}
          </div>
        </Suspense>
        <ToastContainer />
      </body>
    </html>
  );
}
